from typing import Any, Dict, List, Optional

import requests

from config.settings import api_settings, network_settings


class HotelService:
    def __init__(self):
        self.geoapify_api_key = api_settings.geoapify_api_key
        self.timeout = network_settings.request_timeout
        self.ssl_verify = network_settings.geoapify_ssl_verify

        self.geoapify_geocode_url = "https://api.geoapify.com/v1/geocode/search"
        self.geoapify_places_url = "https://api.geoapify.com/v2/places"

    def search_hotels(
        self,
        destination: str,
        budget: Optional[str] = None,
        travelers: Optional[int] = None,
        limit: int = 10,
    ) -> Dict[str, Any]:
        if not destination:
            return {
                "success": False,
                "error": "Destination is required for hotel search.",
                "hotels": [],
            }

        geo_data = self._geocode_location(destination)

        if not geo_data:
            return {
                "success": False,
                "error": f"Could not geocode destination: {destination}",
                "hotels": [],
            }

        accommodation_pois = self._fetch_accommodation_pois(
            latitude=geo_data.get("latitude"),
            longitude=geo_data.get("longitude"),
            limit=limit,
        )

        stay_area_signals = self._build_stay_area_signals(
            destination=destination,
            budget=budget,
            travelers=travelers,
            accommodation_pois=accommodation_pois,
        )

        return {
            "success": True,
            "destination": destination,
            "budget": budget,
            "travelers": travelers,
            "location": geo_data,
            "hotel_data_type": "accommodation_pois_and_stay_area_signals",
            "accommodation_pois": accommodation_pois,
            "stay_area_signals": stay_area_signals,
            "note": (
                "This is raw accommodation and stay-area data from Geoapify. "
                "Final hotel advice should be generated by the final composer using this structured data."
            ),
        }

    def _geocode_location(self, location: str) -> Optional[Dict[str, Any]]:
        if not self.geoapify_api_key:
            return None

        params = {
            "text": location,
            "apiKey": self.geoapify_api_key,
            "limit": 1,
            "filter": "countrycode:in",
        }

        try:
            response = requests.get(
                self.geoapify_geocode_url,
                params=params,
                timeout=self.timeout,
                verify=self.ssl_verify,
            )

            response.raise_for_status()
            data = response.json()

            features = data.get("features", [])

            if not features:
                return None

            properties = features[0].get("properties", {})
            geometry = features[0].get("geometry", {})
            coordinates = geometry.get("coordinates", [])

            lon = None
            lat = None

            if len(coordinates) >= 2:
                lon = coordinates[0]
                lat = coordinates[1]

            return {
                "formatted": properties.get("formatted"),
                "city": properties.get("city") or properties.get("name"),
                "state": properties.get("state"),
                "country": properties.get("country"),
                "latitude": lat,
                "longitude": lon,
            }

        except Exception as e:
            print("[HotelService] Geoapify geocoding failed:")
            print(type(e).__name__, str(e))
            return None

    def _fetch_accommodation_pois(
        self,
        latitude: Optional[float],
        longitude: Optional[float],
        limit: int,
    ) -> List[Dict[str, Any]]:
        if not self.geoapify_api_key:
            return []

        if latitude is None or longitude is None:
            return []

        categories = [
            "accommodation",
            "accommodation.hotel",
            "accommodation.guest_house",
            "accommodation.hostel",
            "accommodation.apartment",
            "accommodation.resort",
        ]

        params = {
            "categories": ",".join(categories),
            "filter": f"circle:{longitude},{latitude},20000",
            "bias": f"proximity:{longitude},{latitude}",
            "limit": limit,
            "apiKey": self.geoapify_api_key,
        }

        try:
            response = requests.get(
                self.geoapify_places_url,
                params=params,
                timeout=self.timeout,
                verify=self.ssl_verify,
            )

            response.raise_for_status()
            data = response.json()

            hotels = []

            for feature in data.get("features", []):
                properties = feature.get("properties", {})
                geometry = feature.get("geometry", {})
                coordinates = geometry.get("coordinates", [])

                poi_lon = None
                poi_lat = None

                if len(coordinates) >= 2:
                    poi_lon = coordinates[0]
                    poi_lat = coordinates[1]

                name = (
                    properties.get("name")
                    or properties.get("address_line1")
                    or properties.get("formatted")
                )

                if not name:
                    continue

                hotels.append(
                    {
                        "name": name,
                        "categories": properties.get("categories", []),
                        "formatted_address": properties.get("formatted"),
                        "latitude": poi_lat,
                        "longitude": poi_lon,
                        "distance_meters": properties.get("distance"),
                        "place_id": properties.get("place_id"),
                    }
                )

            return hotels[:limit]

        except Exception as e:
            print("[HotelService] Geoapify accommodation lookup failed:")
            print(type(e).__name__, str(e))
            return []

    def _build_stay_area_signals(
        self,
        destination: str,
        budget: Optional[str],
        travelers: Optional[int],
        accommodation_pois: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        budget_level = budget or "medium"
        travelers_count = travelers or 1

        density = "low"

        if len(accommodation_pois) >= 8:
            density = "good"
        elif len(accommodation_pois) >= 4:
            density = "moderate"

        return {
            "destination": destination,
            "budget_level": budget_level,
            "travelers": travelers_count,
            "accommodation_density": density,
            "available_poi_count": len(accommodation_pois),
            "suggested_stay_type": self._suggest_stay_type(
                budget=budget_level,
                travelers=travelers_count,
            ),
            "booking_advice_signal": self._booking_advice_signal(
                budget=budget_level,
                accommodation_count=len(accommodation_pois),
            ),
        }

    def _suggest_stay_type(
        self,
        budget: str,
        travelers: int,
    ) -> List:
        if budget == "low":
            return [
                "budget hotel",
                "guest house",
                "hostel",
                "homestay",
            ]

        if budget == "high":
            return [
                "premium resort",
                "boutique hotel",
                "high-rated hotel",
            ]

        if travelers >= 3:
            return [
                "family hotel",
                "serviced apartment",
                "homestay",
                "mid-range resort",
            ]

        return [
            "mid-range hotel",
            "boutique stay",
            "homestay",
        ]

    def _booking_advice_signal(
        self,
        budget: str,
        accommodation_count: int,
    ) -> str:
        if accommodation_count == 0:
            return "No accommodation POIs found from Geoapify. Use final composer to suggest checking major booking platforms."

        if accommodation_count < 4:
            return "Limited accommodation POIs found. Booking early is recommended."

        if budget == "low":
            return "Compare budget hotels and homestays early because low-cost options may fill quickly."

        if budget == "high":
            return "Premium stays should be filtered by amenities, location, and cancellation policy."

        return "Good number of stay options found. Compare location, reviews, and commute convenience."